const actionTypes = {
  LOGIN_SUCCESSFULLY: 'LOGIN_SUCCESSFULLY',
  LOGOUT_SUCCESSFULLY: 'LOGOUT_SUCCESSFULLY',
  UPDATE_PROFILE_SUCCESSFULLY: 'UPDATE_PROFILE_SUCCESSFULLY',

  GET_PARTNER_SUCCESSFULLY: 'GET_PARTNER_SUCCESSFULLY',
  POST_PARTNER_SUCCESSFULLY: 'POST_PARTNER_SUCCESSFULLY',
  CHANGE_PARTNER_LOGO_SUCCESSFULLY: 'CHANGE_PARTNER_LOGO_SUCCESSFULLY',
  ACTIVATE_PARTNER: 'ACTIVATE_PARTNER',

  POST_CLASS_SUCCESSFULLY: 'POST_CLASS_SUCCESSFULLY',
  PATCH_CLASS_SUCCESSFULLY: 'PATCH_CLASS_SUCCESSFULLY',
  DELETE_CLASS_SUCCESSFULLY: 'DELETE_CLASS_SUCCESSFULLY',

  POST_POLICY_SUCCESSFULLY: 'POST_POLICY_SUCCESSFULLY',
  PATCH_POLICY_SUCCESSFULLY: 'PATCH_POLICY_SUCCESSFULLY',
  DELETE_POLICY_SUCCESSFULLY: 'DELETE_POLICY_SUCCESSFULLY',

  GET_VEHICLES_SUCCESSFULLY: 'GET_VEHICLES_SUCCESSFULLY',
  POST_VEHICLE_SUCCESSFULLY: 'POST_VEHICLE_SUCCESSFULLY',
  PATCH_VEHICLE_SUCCESSFULLY: 'PATCH_VEHICLE_SUCCESSFULLY',
  UNREGISTER_VEHICLE_SUCCESSFULLY: 'UNREGISTER_VEHICLE_SUCCESSFULLY',

  GET_JOURNEYS_SUCCESSFULLY: 'GET_JOURNEYS_SUCCESSFULLY',
  POST_JOURNEY_SUCCESSFULLY: 'POST_JOURNEY_SUCCESSFULLY',

  GET_SCHEDULE_SUCCESSFULLY: 'GET_SCHEDULE_SUCCESSFULLY',
  POST_SCHEDULE_SUCCESSFULLY: 'POST_SCHEDULE_SUCCESSFULLY',
  MANIPULATE_SCHEDULE_DETAILS_SUCCESSFULLY:
    'MANIPULATE_SCHEDULE_DETAILS_SUCCESSFULLY',
  CANCEL_SCHEDULE_DETAIL_SUCCESSFULLY: 'CANCEL_SCHEDULE_DETAIL_SUCCESSFULLY',
  REFUND_ALL_TICKETS_SUCCESSFULLY: 'REFUND_ALL_TICKETS_SUCCESSFULLY',

  ADD_CARS_SUCCESSFULLY: 'ADD_CARS_SUCCESSFULLY',
  REMOVE_CAR_SUCCESSFULLY: 'REMOVE_CAR_SUCCESSFULLY',
  GET_CAR_SCHEDULES_SUCCESSFULLY: 'GET_CAR_SCHEDULES_SUCCESSFULLY',
  CANCEL_CAR_SCHEDULE_SUCCESSFULLY: 'CANCEL_CAR_SCHEDULE_SUCCESSFULLY',

  GET_FLIGHT_SCHEDULE_SUCCESSFULLY: 'GET_FLIGHT_SCHEDULE_SUCCESSFULLY',
  POST_FLIGHT_SCHEDULE_SUCCESSFULLY: 'POST_FLIGHT_SCHEDULE_SUCCESSFULLY',
  REFUND_ALL_FLIGHT_TICKETS_SUCCESSFULLY:
    'REFUND_ALL_FLIGHT_TICKETS_SUCCESSFULLY',
  CANCEL_FLIGHT_SCHEDULE_SUCCESSFULLY: 'CANCEL_FLIGHT_SCHEDULE_SUCCESSFULLY',
  MANIPULATE_FLIGHT_SCHEDULE_SUCCESSFULLY:
    'MANIPULATE_FLIGHT_SCHEDULE_SUCCESSFULLY',

  POST_FLIGHT_TICKETS_SUCCESSFULLY: 'POST_FLIGHT_TICKETS_SUCCESSFULLY',

  BEGIN_API_CALL: 'BEGIN_API_CALL',
  API_CALL_ERROR: 'API_CALL_ERROR',
};

export default actionTypes;
