const actionTypes = {
  LOGIN_SUCCESSFULLY: 'LOGIN_SUCCESSFULLY',
  LOGIN_FAILED: 'LOGIN_FAILED',

  REGISTER_SUCCESSFULLY: 'REGISTER_SUCCESSFULLY',
  REGISTER_FAILED: 'REGISTER_FAILED',

  LOGOUT_SUCCESSFULLY: 'LOGOUT_SUCCESSFULLY',
  LOGOUT_FAILED: 'LOGOUT_FAILED',

  BEGIN_API_CALL: 'BEGIN_API_CALL',
  API_CALL_ERROR: 'API_CALL_ERROR',

  GET_ALL_INACTIVE_PARTNERS_SUCCESSFULLY:
    'GET_ALL_INACTIVE_PARTNERS_SUCCESSFULLY',

  UPDATE_ACTIVE_PARTNER_SUCCESSFULLY: 'UPDATE_ACTIVE_PARTNER_SUCCESSFULLY',
};

export default actionTypes;
