const actionTypes = {
  LOGIN_SUCCESSFULLY: 'LOGIN_SUCCESSFULLY',
  LOGIN_FAILED: 'LOGIN_FAILED',

  REGISTER_SUCCESSFULLY: 'REGISTER_SUCCESSFULLY',
  REGISTER_FAILED: 'REGISTER_FAILED',

  LOGOUT_SUCCESSFULLY: 'LOGOUT_SUCCESSFULLY',
  LOGOUT_FAILED: 'LOGOUT_FAILED',

  BEGIN_API_CALL: 'BEGIN_API_CALL',
  API_CALL_ERROR: 'API_CALL_ERROR',

  UPDATE_PROFILE_SUCCESSFULLY: 'UPDATE_PROFILE_SUCCESSFULLY',
  BOOKING_SUCCESSFULLY: 'BOOKING_SUCCESSFULLY',

  GET_SCHEDULES_SUCCESSFULLY: 'GET_SCHEDULES_SUCCESSFULLY',
  GET_SCHEDULES_EXCHANGE_SUCCESSFULLY: 'GET_SCHEDULES_EXCHANGE_SUCCESSFULLY',
  // GET_CARS_SUCCESSFULLY: 'GET_CARS_SUCCESSFULLY',
  // GET_FLIGHT_TICKETS_SUCCESSFULLY: 'GET_FLIGHT_TICKETS_SUCCESSFULLY',
  // GET_CAR_SCHEDULES_SUCCESSFULLY: 'GET_CAR_SCHEDULES_SUCCESSFULLY',

  GET_REFUND_TICKET_SUCCESSFULLY: 'GET_REFUND_TICKET_SUCCESSFULLY',

  SUCCESS_PAYMENT: 'SUCCESS_PAYMENT',
  END_OF_SESSION: 'END_OF_SESSION',
  RESET_PAYMENT_STATUS: 'RESET_PAYMENT_STATUS',
};

export default actionTypes;
