import {
  faHome,
  faPercent,
  faAward,
  faReceipt,
  faPaperPlane,
  faHotel,
  faSynagogue,
  faParking,
  faCarAlt,
  faSubway,
  faMailBulk,
  faPhoneAlt,
  faQuestionCircle,
  faMobile,
  faBriefcase,
  faClone,
  faQuestion,
} from '@fortawesome/free-solid-svg-icons';

export const DrawerData = [
  [
    {
      iconId: 1,
      icon: faHome, 
      iconText: 'Trang chủ',
      path: '',
    },
    {
      iconId: 2,
      icon: faReceipt,
      iconText: 'Đặt chỗ của tôi',
      path: '',
    },
    {
      iconId: 3,
      icon: faMailBulk,
      iconText: 'Hộp thư của tôi',
      path: '',
    },
    {
      iconId: 4,
      icon: faAward,
      iconText: 'Đã lưu',
      path: '',
    },
    {
      iconId: 5,
      icon: faPhoneAlt,
      iconText: 'Liên hệ với chúng tôi',
      path: '',
    },
    {
      iconId: 6,
      icon: faQuestionCircle,
      iconText: 'Trợ giúp',
      path: '',
    },
    {
      iconId: 7,
      icon: faMobile,
      iconText: 'Tải ứng dụng',
      path: '',
    },
  ],
  [
    {
      iconId: 8,
      icon: faPercent,
      iconText: 'Khuyến mãi',
      path: '',
    },
    {
      iconId: 9,
      icon: faPaperPlane,
      iconText: 'Vé máy bay',
      path: '',
    },
    {
      iconId: 10,
      icon: faHotel,
      iconText: 'Khách sạn',
      path: '',
    },
    {
      iconId: 11,
      icon: faSynagogue,
      iconText: 'Combo tiết kiệm',
      path: '',
    },
    {
      iconId: 12,
      icon: faParking,
      iconText: 'Đưa đón máy bay',
      path: '',
    },
    {
      iconId: 13,
      icon: faAward,
      iconText: 'Xperience',
      path: '',
    },
    {
      iconId: 14,
      icon: faCarAlt,
      iconText: 'Cho thuê xe',
      path: '',
    },
    {
      iconId: 15,
      icon: faSubway,
      iconText: 'JR Pass',
      path: '',
    },
  ],
  [
    {
      iconId: 16,
      icon: faBriefcase,
      iconText: 'Tuyển dụng',
      path: '',
    },
    {
      iconId: 17,
      icon: faClone,
      iconText: 'Traveloka Blog',
      path: '',
    },
    {
      iconId: 18,
      icon: faQuestion,
      iconText: 'Cách đặt chỗ',
      path: '',
    },
  ],
];
